### ISSUE TITLE
Finer device selection

### ISSUE THREAD

**Issue by edmont** [hanyazou/dfu-util#1]
Currently the following option exists:
```
  -d --device <vendor>:<product>[,<vendor_dfu>:<product_dfu>]
                                Specify Vendor/Product ID(s) of DFU device
```
But there is no option to choose a device when multiple devices with the same vendor and product IDs are present. It would be handful being able to select a device by its _devnum_ or _serial_. Is that even possible?

**Comment by hanyazou** [comment]
This repo is just a copy of the official repo at git://git.code.sf.net/p/dfu-util/dfu-util . Please see the official home page http://dfu-util.sourceforge.net/.
